Travis: Work around frequent build failures
The build will consistently fail for days at a time with:

error: http://pool.sks-keyservers.net/pks/lookup?op=get&search=0x85C7044E033FDE16: import read failed(-1).
warning: u 0x2205de0 ctrl 0x2207120 nrefs != 0 (pool.sks-keyservers.net http)

I have a hunch that this is related to the CentOS 5 Docker container, so
this commit causes Travis to download the RPM signing keys outside of
the container and share them with the container.